//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pioneer.Consultancy.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PioneerWcfService.CompositeType GetDataUsingDataContract(PioneerWcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PioneerWcfService.CompositeType> GetDataUsingDataContractAsync(PioneerWcfService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TakeProjectDetail", ReplyAction="http://tempuri.org/IService1/TakeProjectDetailResponse")]
        int TakeProjectDetail(PioneerTech.Models.ProjectModel myProject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TakeProjectDetail", ReplyAction="http://tempuri.org/IService1/TakeProjectDetailResponse")]
        System.Threading.Tasks.Task<int> TakeProjectDetailAsync(PioneerTech.Models.ProjectModel myProject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Pioneer.Consultancy.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Pioneer.Consultancy.ServiceReference1.IService1>, Pioneer.Consultancy.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PioneerWcfService.CompositeType GetDataUsingDataContract(PioneerWcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PioneerWcfService.CompositeType> GetDataUsingDataContractAsync(PioneerWcfService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int TakeProjectDetail(PioneerTech.Models.ProjectModel myProject) {
            return base.Channel.TakeProjectDetail(myProject);
        }
        
        public System.Threading.Tasks.Task<int> TakeProjectDetailAsync(PioneerTech.Models.ProjectModel myProject) {
            return base.Channel.TakeProjectDetailAsync(myProject);
        }
    }
}
